sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
  - pip install -U pip setuptools
  - pip install tox-travis coveralls
script: tox
after_success: coveralls
branches:
  only:
    - develop
    - master
    - /^\d+.\d+.\d+$/
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: 3.6
